const modules=[
 {title:'Verb to be',level:'A1',questions:[['I ___ at home now.',['am','is','are'],0],['They ___ from Spain.',['am','is','are'],2],['___ she tired?',['Am','Is','Are'],1],['My keys ___ on the table.',['is','are','am'],1],['We ___ not late.',['is','are','am'],1]]},
 {title:'Present Simple',level:'A1',questions:[['He ___ coffee every morning.',['drink','drinks','is drinking'],1],['___ you work on Saturdays?',['Do','Does','Are'],0],['My sister ___ TV often.',['doesn’t watch','don’t watch','isn’t watch'],0],['I ___ to music after work.',['listen','listens','am listen'],0],['Where ___ your parents live?',['do','does','are'],0]]},
 {title:'Present Continuous',level:'A1',questions:[['Listen! The baby ___.',['cries','is crying','cry'],1],['We ___ dinner right now.',['cook','are cooking','cooked'],1],['She ___ today.',['doesn’t work','isn’t working','not working'],1],['___ they waiting outside?',['Do','Are','Is'],1],['I ___ a new book this week.',['read','am reading','have read'],1]]},
 {title:'Past forms',level:'A2',questions:[['Yesterday I ___ my friend.',['see','saw','have seen'],1],['They ___ dinner at 7 pm.',['were having','had','have'],0],['___ you go out last night?',['Did','Do','Have'],0],['She ___ when I called.',['slept','was sleeping','has slept'],1],['We ___ not at home yesterday.',['weren’t','aren’t','haven’t'],0]]},
 {title:'Present Perfect',level:'A2',questions:[['I ___ this film before.',['saw','have seen','am seeing'],1],['She ___ her keys.',['has lost','lost','is losing'],0],['___ you ever been to Rome?',['Did','Have','Are'],1],['They haven’t finished ___.',['yet','ago','last'],0],['We ___ here since 2022.',['live','have lived','lived'],1]]},
 {title:'Future & modals',level:'A2',questions:[['I think it ___ tomorrow.',['rains','will rain','is rain'],1],['You ___ wear a seat belt.',['must','must to','are must'],0],['___ I open the window?',['Should','Will','May'],2],['She ___ visit us next week.',['is going to','goes to','has to going'],0],['You ___ smoke here.',['mustn’t','don’t must','not must'],0]]},
 {title:'Articles & nouns',level:'A2',questions:[['I need ___ umbrella.',['a','an','the'],1],['We visited ___ British Museum.',['a','the','—'],1],['There is ___ milk in the fridge.',['many','much','a few'],1],['How ___ people came?',['much','many','any'],1],['She bought two ___.',['child','children','childs'],1]]},
 {title:'Prepositions',level:'A2',questions:[['The train leaves ___ Monday.',['in','on','at'],1],['I usually get up ___ 7.',['in','on','at'],2],['They arrived ___ the airport early.',['at','in','on'],0],['This book belongs ___ me.',['for','to','at'],1],['He is good ___ maths.',['in','at','on'],1]]},
 {title:'Comparatives',level:'B1',questions:[['This bag is ___ than mine.',['more cheap','cheaper','the cheapest'],1],['Anna is the ___ student here.',['more careful','carefullest','most careful'],2],['My room isn’t ___ yours.',['as big as','so big than','bigger as'],0],['The weather is getting ___.',['cold','colder','more coldest'],1],['This is ___ book I have read.',['better','the best','the better'],1]]},
 {title:'Conditionals',level:'B1',questions:[['If it rains, we ___ at home.',['stay','will stay','would stay'],1],['If I had more time, I ___ French.',['learn','will learn','would learn'],2],['If she had studied, she ___ the test.',['would pass','would have passed','will pass'],1],['If you heat ice, it ___.',['melts','will melt','would melt'],0],['If they call, I ___ them.',['help','will help','would help'],1]]}
];
const grid=document.querySelector('#moduleGrid'),card=document.querySelector('#quizCard');let currentModule,currentQuestion,score,answered=false;
function renderModules(){grid.innerHTML=modules.map((m,i)=>`<button class="module-card" data-module="${i}"><span>${m.level}</span><h2>${m.title}</h2><p>5 вопросов · ключ после ответа</p><i>→</i></button>`).join('');document.querySelectorAll('.module-card').forEach(b=>b.onclick=()=>start(+b.dataset.module))}
function start(index){currentModule=modules[index];currentQuestion=0;score=0;grid.hidden=true;card.hidden=false;renderQuestion()}
function renderQuestion(){answered=false;const q=currentModule.questions[currentQuestion];document.querySelector('#quizUnit').textContent=`${currentModule.title.toUpperCase()} · ${currentModule.level}`;document.querySelector('#quizProgress').textContent=`${currentQuestion+1} / ${currentModule.questions.length}`;document.querySelector('#quizQuestion').textContent=q[0];document.querySelector('#quizFeedback').textContent='';document.querySelector('#nextQuestion').hidden=true;document.querySelector('#quizOptions').innerHTML=q[1].map((x,i)=>`<button data-choice="${i}">${x}</button>`).join('');document.querySelectorAll('#quizOptions button').forEach(b=>b.onclick=()=>answer(+b.dataset.choice))}
function answer(choice){if(answered)return;answered=true;const q=currentModule.questions[currentQuestion],ok=choice===q[2];if(ok)score++;document.querySelectorAll('#quizOptions button').forEach((b,i)=>{b.disabled=true;if(i===q[2])b.classList.add('correct');if(i===choice&&!ok)b.classList.add('wrong')});document.querySelector('#quizFeedback').textContent=ok?'Верно!':'Неверно. Правильный вариант выделен зелёным.';document.querySelector('#quizFeedback').className=`quiz-feedback ${ok?'good':'bad'}`;const next=document.querySelector('#nextQuestion');next.hidden=false;next.textContent=currentQuestion===currentModule.questions.length-1?`Результат: ${score} / ${currentModule.questions.length} →`:'Следующий вопрос →'}
document.querySelector('#nextQuestion').onclick=()=>{if(currentQuestion===currentModule.questions.length-1){card.hidden=true;grid.hidden=false;return}currentQuestion++;renderQuestion()};document.querySelector('#quizBack').onclick=()=>{card.hidden=true;grid.hidden=false};renderModules();
